# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yxu <yxu@student.42abudhabi.ae>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/08/24 02:28:20 by yxu               #+#    #+#              #
#    Updated: 2022/08/24 02:28:34 by yxu              ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

OUTPUT = do-op

CC = gcc
CFLAGS = -Wall -Wextra -Werror

all: ${OUTPUT}

clean:
	rm -f .DS_Store

fclean: clean
	rm -f ${OUTPUT}

.PHONY: all clean fclean
